<?php
/**
 * Created by PhpStorm.
 * User: jerryzst
 * Date: 2019/9/2 0002
 * Time: 14:00
 */

namespace easywa\wapay;


use easywa\wapay\Common\BaseHandle;
use easywa\wapay\Common\WeiXin\WxBaseHandle;
use easywa\wapay\Trade\WeiXin\TradeAppPay;
use easywa\wapay\Trade\WeiXin\TradeMwebPay;
use easywa\wapay\Trade\WeiXin\TradePubPay;
use easywa\wapay\Trade\WeiXin\TradeQrPay;
use yii\base\Component;

class TradePay extends Component
{
    protected $payWay;
    
    public  $config;

    public  $channel;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        
        if (empty($this->channel)) {
            throw new PayException('支付渠道不可为空！');
        }

        if (empty($this->config)) {
            throw new PayException('支付配置不可为空！');
        }

        try {
            switch ($this->channel) {
                case Config::WX_CHANNEL_QR:
                    $this->payWay = new TradeQrPay($this->config);
                    break;
                case Config::WX_CHANNEL_PUB:
                    $this->payWay = new TradePubPay($this->config);
                    break;
                case Config::WX_CHANNEL_APP:
                    $this->payWay = new TradeAppPay($this->config);
                    break;
                case Config::WX_CHANNEL_MWEB:
                    $this->payWay = new TradeMwebPay($this->config);
                    break;
                default :
                    throw new PayException('不支持该支付渠道');
            }
        } catch (PayException $exception) {
            throw $exception;
        }
    }

    /**
     * Notes:
     * @Description:外部暴露接口
     * @Author: jerryzst
     * @Date: 2019/9/3 0003
     * @Time: 9:29
     * @param array $data
     * @return mixed
     * @throws PayException
     */
    public function run(array $data)
    {
        if (!$this->payWay instanceof BaseHandle) {
            throw new PayException('请检查初始化是否正确');
        }
        try {
            return $this->payWay->handle($data);
        } catch (PayException $e) {
            throw $e;
        }
    }
}